- hosts: ceph-mon 
  vars:
    password: $6$5RQd8yrU$f0i.pQqmg/f8komlnMqhxLnadTXjCfP5bmFj.a9uAiS7nZPBYVd34TeWiUMTLX2Fxxpnw30fEl3/MGzaYcd8p1 

  tasks:

    - name: Add CEPH Admin User 
      user: name=ceph-admin password={{password}}

    - name: Enable the Extra Packages for Enterprise Linux (EPEL) repository 
      yum:
       name: epel-release
       state: latest

    - name: Copy files hosts
      copy:
       src: ./files/hosts
       dest: /etc/hosts

    - name: Copy file ceph-deploy.repo
      copy:
       src: ./files/ceph-deploy.repo
       dest: /etc/yum.repos.d/ceph-deploy.repo

    - name: Add ceph-admin to sudoers
      copy:
       src: ./files/ceph-admin
       dest: /etc/sudoers.d/ceph-admin
       mode: 0440

    - name: Set ceph-admin public SSH authorized key
      authorized_key:
       user: ceph-admin
       state: present
       key: "{{ lookup('file', '/home/ceph-admin/.ssh/authorized_keys') }}"

    - name: Copy file selinux config
      copy:
       src: ./files/config
       dest: /etc/selinux/config

    - name: Stop SELinux
      selinux:
       state: disabled       

    - name: Stop and disable firewalld
      service:
       name: firewalld
       state: stopped
       enabled: False
